```{r}

h_n <- "lung|neck|geal"


cancers %>% 
    filter(
        str_detect(traits, "squamous")
    ) %>% 
    mutate(
        head_neck =  if_else(
            str_detect(traits, "oral cavity|aryn|aerodigest") | (
                str_detect(traits, "squamous") & (str_detect(traits, h_n) | str_detect(tolower(DISEASE.TRAIT), h_n))
                ), 
            TRUE, FALSE) ,
        skin_non_melanoma =  if_else(
            str_detect(traits, "skin|basal|keratinocyte|squamous") & !str_detect(traits, h_n) & !str_detect(tolower(DISEASE.TRAIT), h_n), TRUE, FALSE),
        lung =               if_else(str_detect(traits, "lung") & !str_detect(traits, "squamous"), TRUE, FALSE),
        traits = str_trunc(traits, 50)
    ) %>% 
    count(PUBMEDID, DISEASE.TRAIT, traits, head_neck, skin_non_melanoma, lung) %>% arrange(head_neck, skin_non_melanoma)
    # readr::write_csv('test.csv')
    
```

```{r}
final %>% 
    filter(cancer_class == "cancer_multiple_or_unspecified") %>%
    count(PUBMEDID, DISEASE.TRAIT, cancer_class)
```

```{r}
cancers %>% 
    filter(total>1)
```

