---
title: "R Notebook"
output: html_notebook
---
```{r setup}
library(dplyr)
library(stringr)
library(rvest)

reportdir <- file.path(rprojroot::find_rstudio_root_file(), "reporting")

if(!exists("gwas_classified")){
    gwas_classified <- readr::read_csv("../../data/gwas_cancer_classifications.csv")
}
```

```{r to refresh publication dataset, echo=FALSE, include=FALSE, eval=FALSE}
source(file.path(rprojroot::find_rstudio_root_file(), "reporting", "classify_gwas_cancer_pubs.R"))
source(file.path(reportdir, "get_pub_data.R"))
```


```{r}
# Define significance thresholds for "Definitely significant" vs. "Borderline significant"
sig <- 5 * 10^-8
min_sig <- 1 * 10^-7

breast_pubs <- gwas_classified %>% 
    filter( # Restrict analysis to breast cancer, not including studies assessing receptor status
        cancer_class == "breast",
        !str_detect(DISEASE.TRAIT, "status")
        ) %>%
    mutate( # Clean and extract sample sizes (case/control) from initial test set
        INITIAL.SAMPLE.SIZE = str_replace(INITIAL.SAMPLE.SIZE, " affected", "cases"),
        INITIAL.SAMPLE.SIZE = str_replace(INITIAL.SAMPLE.SIZE, " unaffected", "controls"),
        INITIAL.SAMPLE.SIZE = str_replace_all(INITIAL.SAMPLE.SIZE, "(?<=[a-z]),", ";"),
        INITIAL.SAMPLE.SIZE = str_remove_all(INITIAL.SAMPLE.SIZE, ","),
        init_cases          = str_extract(INITIAL.SAMPLE.SIZE, "[0-9]+(?=.*cases)"),
        init_controls       = str_extract(INITIAL.SAMPLE.SIZE, "(?<=; )[0-9]+(?=.*controls)"),
    ) %>%
    mutate( # Clean and extract sample sizes (case/control) from replication set
        internally_replicated   = !is.na(REPLICATION.SAMPLE.SIZE),
        REPLICATION.SAMPLE.SIZE = str_replace_all(REPLICATION.SAMPLE.SIZE, "(?<=[a-z]),", ";"),
        REPLICATION.SAMPLE.SIZE = str_remove_all(REPLICATION.SAMPLE.SIZE, ","),
        rep_cases               = str_extract(REPLICATION.SAMPLE.SIZE, "[0-9]+(?=.*cases)"),
        rep_controls            = str_extract(REPLICATION.SAMPLE.SIZE, "(?<=; )[0-9]+(?=.*controls)"),
    ) %>%
    mutate( # Clean and extract statistical test data
        X95..CI..TEXT. = str_replace(X95..CI..TEXT., "\\(", "\\["),
        X95..CI..TEXT. = str_replace(X95..CI..TEXT., "\\)", "\\]"),
        lower_ci       = if_else(
            str_detect(X95..CI..TEXT.,"NR"), "NR", str_extract(X95..CI..TEXT., '(?<=\\[)[0-9.]+') 
            ),
        upper_ci       = if_else(
            str_detect(X95..CI..TEXT.,"NR"), "NR", str_extract(X95..CI..TEXT., '(?<=-)[0-9.]+(?=\\])')
        )
    ) %>%
    mutate( # Genome wide significance
        gw_sig = P.VALUE <= (sig),
        gw_borderline = P.VALUE > (sig) & P.VALUE <= (min_sig),
        lower_ci = as.numeric(lower_ci),
        upper_ci = as.numeric(upper_ci)
        ) %>% 
    # select(REPLICATION.SAMPLE.SIZE, rep_cases, rep_controls) %>%
    # filter(is.na(rep_cases) | is.na(rep_controls))
    select(
        PUBMEDID, STUDY, SNPS, 
        DISEASE.TRAIT, MAPPED_TRAIT, #cancer_class,
        INITIAL.SAMPLE.SIZE, init_cases, init_controls, 
        internally_replicated, REPLICATION.SAMPLE.SIZE, rep_cases, rep_controls, 
        gw_sig, gw_borderline, P.VALUE, OR.or.BETA, X95..CI..TEXT., lower_ci, upper_ci,
        abstract, doi
    ) %>% 
    readr::write_csv("../../data/breast_cancer_pubs.csv")
```

```{r}
breast_pubs %>% 
    # count(gw_sig, gw_borderline, internally_replicated) %>% 
    filter(
        # gw_sig == TRUE | 
            gw_borderline == TRUE
        ) %>% 
    select(PUBMEDID, P.VALUE, lower_ci, OR.or.BETA, upper_ci)
```

```{r}
# SNPs reaching GW significance AND reported by more than one study
sig_rep_snps <- breast_pubs %>% 
    filter(
        gw_sig==TRUE |gw_borderline==TRUE
        ) %>% 
    count(SNPS) %>% 
    filter(n>1)
```

```{r}
breast_pubs %>% 
    filter(SNPS %in% sig_rep_snps$SNPS) %>% 
    distinct(PUBMEDID) %>% 
    mutate(
        pm_url = file.path("https://www.ncbi.nlm.nih.gov/pubmed", PUBMEDID)
    )
```
```{r}
    # Construct query URL using NCBI EUtil API and query pubmed for PMC ids using PMIDs
source(file.path(rprojroot::find_rstudio_root_file(), "functions", "ncbi_eutil_functions.R"))

id_str <- breast_pubs %>% 
    filter(SNPS %in% sig_rep_snps$SNPS) %>% 
    distinct(PUBMEDID) %>% 
    pull() %>% paste(collapse = ",")
    
link_url <- eutil_link_url_generator(dbfrom = "pubmed", db = "pmc", ids = id_str)
rvest::html()
id_xml <- read_xml(link_url)
```





